### ISSUE TITLE
CIENTISTA DE DADOS JÚNIOR l REMOTO l INTELLIMETRI

### ISSUE THREAD

**Issue by gabrielanatascha** [datascience-br/vagas#111]
Oportunidade para Cientista de Dados Júnior - Python (remoto) - EMPRESA: INTELLIMETRI

Nós estamos procurando um Cientista de Dados Júnior para se juntar ao nosso time. O candidato ideal tem experiência com programação em Python e está animado para trabalhar em projetos de análise de dados complexos. Este é um papel vital no nosso time, onde o cientista de dados júnior será responsável por coletar, limpar, transformar e modelar dados para ajudar a tomar decisões estratégicas.

Responsabilidades:

Coletar, limpar e preparar dados para análise, utilizar técnicas estatísticas para modelar e analisar dados, trabalhar com equipes de negócios para entender os requisitos de análise de dados e fornecer insights, criar visualizações de dados (dashboards) para comunicar resultados e insights, ajudar a implementar e manter sistemas de gerenciamento de dados, continuar a aprender e se manter atualizado com as últimas tendências e técnicas em ciência de dados.

Requisitos:

Experiência com programação em Python, conhecimento de bibliotecas de ciência de dados como NumPy, Pandas e Scikit-learn, conhecimento de técnicas estatísticas e modelagem de dados, forte capacidade de comunicação e habilidade de trabalhar em equipe, paixão por aprender e trabalhar com dados.

Desejável:

Experiência com SQL e bancos de dados relacionais, experiência com ferramentas de visualização de dados, como Looker Studio ou Power BI, conhecimento de machine learning e aprendizado automático, certificação técnica em Google Cloud.

Este é um cargo júnior, portanto, é uma oportunidade incrível para alguém que está começando sua carreira em ciência de dados e está animado para aprender e crescer em uma empresa dinâmica.

Remuneração CLT: 5K + benefícios.

Se você tem interesse na oportunidade, envie seu currículo para: gabriela@escolhacertarh.com.br

**Comment by jacksontenorio8** [comment]
Prezada Gabriela Natascha, espero que seu dia esteja indo bem! Meu nome é
Jackson Tenorio e estou há um tempo fazendo serviço voluntário para algumas
pessoas da faculdade, entre eles mineração de dados em redes sociais e
análise de dados. Estou muito interessado em trabalhar para Intellimetri e
posso começar hoje mesmo. Sua missão em guiar a transformação digital dos
negócios. E vontade de abraçar desafios. Me inspiram! Os produtos que vocês
criam e os valores que vocês defendem fazem com que a Intellimetri seja o
local de trabalho ideal para mim. Um pouco sobre mim, eu Jackson Tenorio,
tenho 35 anos e atualmente moro em Campinas/SP, Brasil, tenho alguns
projetos no meu portifolio pessoal é: https://github.com/jacksontenorio8.
Acho que essas experiências me tornaram um ótimo candidato para você.
Informe-me se precisar de mais alguma coisa da minha parte. Estou ansioso
para ouvir de você! Posso ser contatado em ***@***.***,
https://www.linkedin.com/in/jacksontenorio8 e +5519997894850.

Att.,

Jackson Tenorio

Em qua., 18 de jan. de 2023 às 15:51, gabrielanatascha <
***@***.***> escreveu:

**Comment by ErickBezerrar** [comment]
Prezado(a) INTELLIMETRI

Estou escrevendo para firmar meu interesse na vaga de Cientista de Dados Júnior na INTELLIMETRI. Com menos de 1 ano de experiência na área de atuação, eu acredito que tenho algumas habilidades e competências necessárias para ser uma contribuição valiosa para a equipe da INTELLIMETRI, pois vontade de aprender eu tenho.

Estou graduando em Sistemas de Informação pela UFRN e possuo habilidades em python, nas bibliotecas Numpy, pandas e yfinance. Além disso, minha experiência no mercado de trabalho é quase zero, pois antes de tentar essa vaga eu trabalhei na BYTEJR, empresa Júnior da UFRN.

Estou empolgado com a possibilidade de fazer parte da equipe da INTELLIMETRI, que tem uma reputação bem sólida no mercado e acredito que uma boa dinâmica também. Estou ansioso para conversar com você sobre como minhas habilidades e experiências podem contribuir para o sucesso da empresa. OBS: Tenho muita curiosidade de trabalhar e aprender.

Por favor, meu currículo encontra-se anexado para revisão. Ficarei feliz em discutir meu histórico profissional e minhas qualificações  pessoalmente em uma entrevista.

Muito obrigado por considerar minha candidatura a INTELLIMETRI.

Atenciosamente,

Erick Bezerra

**Comment by AllexGN** [comment]
Boa tarde Gabriela, tudo bem ?

Meu nome é Alex e vim por meio da sua publicação no LinkedIn, atualmente estou cursando o último semestre do curso Análise e Desenvolvimento de Sistemas da Universidade Anhembi Morumbi e realizando uma especialização em "Análise de Dados" pela Escola Britânica de Artes Criativas e Tecnologia - EBAC. Sou uma pessoa com ambição em adquirir novos conhecimentos, tenho facilidade em aprender e sou um profissional proativo em todas as tarefas nas quais sou responsável, com um forte senso de trabalho em equipe e disposição para superar desafios e obstáculos. Busco atualmente oportunidades na área da tecnologia e Análise de Dados. Meu currículo encontra-se anexo para revisão no seu e-mail. Ficarei agradecido em conversar a respeito desta oportunidade.

Fico no aguardo de seu retorno !

Atenciosamente
Alex Gonçalves Nascimento

**Comment by DevBrunoo** [comment]
Quero demonstrar meu interesse para vaga de dados que é uma coisa que venho me especializando cada vez mais. Meu nome é Bruno Oliveira e atuo como engenheiro de software e web design desde 2021. Durante esse período, trabalhei em projetos voluntários, pessoais e corporativos, onde obtive experiência em diversas linguagens de programação. Atualmente, estou cursando bacharelado em engenharia da computação na UNIFRAN, uma das maiores faculdades da América do Sul. Me formei em introdução à ciência da computação na plataforma Edex, desenvolvida pelo MIT e Harvard. Diariamente, divulgo meus projetos no Instagram e GitHub, contribuindo para a evolução tecnológica que tanto amo.

**Comment by carlosmurilosantos** [comment]
Ola, Gabriela tudo bem? Meu nome e Carlos e gostaria de demonstrar interesse na oportunidade de Cientista de dados Junior, soube dessa oportunidade atraves do anuncio no  Github e gostaria de participar do processo seletivo.
Atualmente estou estudando Analise e desenvolvimento de sistemas, possuo certificação profissional em Analise de dados Google Data Analytics pela Coursera, tenho experiência em estagio com Metodologias Ageis e Engenharia de Software. Embora nao tenha experiência profissional como cientista de dados, possuo conhecimento nas linguagens: Python, R, SQL e conheço Jupyter Notebook.
Tenho conhecimento em analise de dados com biblitoecas Numpy, Pandas, ferramentas de dataviz Tableau e Power BI.
Estou iniciando carreira em TI e me identifico com area de dados e sou pessoa que sempre está aprendendo, buscando estar conhecendo novos aprendizados. 
Gostaria de encaminhar meu currículo em anexo por email. Desde ja, agradeço a atenção.

**Comment by pulpor** [comment]
Olá, Gabriela 

  Sou um entusiasta apaixonado por Python desde que descobri seu potencial no mundo das finanças. Já fiz diversos cursos na área e me aprofundei ainda mais durante meu curso de desenvolvimento full stack na Trybe, onde tive a oportunidade de aprender com grandes especialistas. Além disso, adquiri conhecimentos em análise de dados na EBAC.

Estou enviando meu currículo para a vaga de Cientista de Dados Júnior na IntelliMetri, pois acredito que minha experiência e paixão por Python combinam perfeitamente com os requisitos da posição. Gostaria de destacar que possuo um portfólio no GitHub, um perfil no LinkedIn, participei de competições no Kaggle e tenho um portfólio de projetos que demonstram minhas habilidades e dedicação.

Estou empolgado com a oportunidade de contribuir para a equipe da IntelliMetri, ajudando a coletar, limpar e modelar dados para tomar decisões estratégicas. Além disso, estou sempre buscando aprender e me manter atualizado com as últimas tendências e técnicas em ciência de dados.

Agradeço a consideração e estou disponível para discutir mais sobre como posso agregar valor à equipe. Aguardo ansiosamente o contato para a próxima etapa do processo seletivo.

Atenciosamente, 
Att, Leonardo Pulpor. 😊

**Comment by cleitoncarillo** [comment]
Prezados, tudo bem?

   Em virtude da minha carreira acadêmica e profissional, como Mestre de Física, possuo sólidos conhecimentos em Matemática, Estatística e Física, podendo contribuir consideravelmente para a área de dados. Em adição, tenho experiência com as seguintes ferramentas para análise, interpretação e visualização de dados: Python (voltado para área de dados), SQL, Microsoft Power BI, Scikit-learn, R, Fortran 77 (apesar de antiga, muito usada por pesquisadores da ciência) e MATLAB.
   Em razão da minha experiência em sala de aula, como professor do ensino superior, possuo facilidade de comunicação, ótima adaptação ao ambiente de trabalho, estou sempre disposto a compartilhar conhecimentos e busco o aperfeiçoamento contínuo, tendo mentalidade de empreendedor e, principalmente, resolvedor de problemas.
   Bacharel em Física, com mestrado em Astrofísica, tenho experiência em análise de dados científicos, tendo o meu TCC e Dissertação de Mestrado, por exemplo, fundamentado em tais dados. Desde o ano de 2015 atuo como professor no Ensino Superior, na Faculdade Anhanguera, possuindo uma sólida bagagem de conhecimentos e disciplinas ministradas no cursos de Engenharia Civil, Elétrica, Mecânica e Produção, tais como: Mecânica dos Fluidos, Hidráulica e Hidrometria, Fenômenos de Transporte, Eletrotécnica Geral, Eletromagnetismo, Termodinâmica, as Físicas I, II e III, como também as disciplinas de Cálculo II e III. Além disso, recentemente ministrei disciplinas no curso de Licenciatura em Matemática EAD/UAB pela Universidade Estadual de Santa Cruz (UESC) e sou aluno do curso técnico em Ciência de Dados, pela Faculdade Pitágoras.

Atenciosamente,
Cleiton Carillo

**Comment by Msamuelsons** [comment]
Sou um estudante de Ciência de Dados com uma paixão profunda pela área. Desde o ensino médio, fui atraído pelo mundo dos dados, o que me levou a me especializar e aprofundar meus conhecimentos nesse campo. Completei um curso técnico em Desenvolvimento de Software pelo Instituto Federal do Piauí e atualmente estou cursando Análise e Desenvolvimento de Sistemas, além de Ciência de Dados. Estou constantemente buscando oportunidades para expandir minha expertise e contribuir para o campo da Ciência de Dados. Estou em busca de oportunidades que me permitam aplicar minha paixão e habilidades, e continuar minha jornada de aprendizado nesse mundo fascinante dos dados.
