### ISSUE TITLE
[Analista de Dados/ Ciências de Dados Júnior e Pleno] - Remoto - HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [datascience-br/vagas#112]
[Analista de Dados/ Ciências de Dados Júnior e Pleno] - Remoto. Júnior: entre R$2.900 e R$4.300 - Pleno: entre R$4.800 e R$5.820.

Experiência requerida obrigatória:
•	Júnior com mais de 1 ano de experiência e Pleno com mais de 2 anos de experiência (experiência comprovada);
•	Programação em R ou Python;
•	Estruturação de banco de dados;
•	Vivência com técnicas tradicionais usadas em Ciências de Dados (classificação, regressão, clustering, teste A/B).

Requisitos Desejáveis:
•	Software de visualização de dado;
•	Ferramenta de Versionamento (Git).

Salário
•	Júnior: entre R$2.900 e R$4.300
•	Pleno: entre R$4.800 e R$5.820

Benefícios
•	Contrato CLT
•	Vale transporte
•	Gympass
•	Plano de Saúde Bradesco
•	Plano Odontológico Bradesco
•	Plano de Carreira
•	PDI.

Encerra até 17/02/2023

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by shamyrapequenoo** [comment]
olá, estou em busca de uma oportunidade de analista de dados jr. Se houver estou disponível...
