### ISSUE TITLE
[remoto] Cientista de Dados Sênior [CLT até 11k] 

### ISSUE THREAD

**Issue by ThabataMattos** [datascience-br/vagas#45]
## Descrição da vaga
Analisar e explorar grandes bases de dados;
Criar e suportar dashboards e visualização;
Tratar e processar grandes massas de dados;
Desenvolver sistemas inteligentes (machine learning);
Suportar o deployment de suas soluções.

## Local
Remoto

#### Obrigatórios:
Experiência em escrever códigos reutilizáveis e construir pipelines de dados resilientes em ambientes em nuvem;
Estatística;
Machine Learning; Redes neurais; Data viz; SQL;  Linux e Shell script; Cloud Computing, preferencialmente AWS nas seguintes ferramentas (S3, EC2, IAM, Sagemaker); controle de versões (Git); Data Lake e DW;

Inglês  intermediário.

## Contratação
- CLT

## Como se candidatar
Por favor envie um e-mail para thabata.mattos@rheserva.com.br

**Comment by nathanmrtns** [comment]
@ThabataMattos Há vagas para júnior?

**Comment by ThabataMattos** [comment]
@nathanmrtns com este escopo de vaga tenho apenas esta posição sênior. Porém, tenho muitos parceiros e algumas outras oportunidades. Se fizer sentido pra você, podemos agendar uma conversa e encontrar um desafio que seja bacana pra você!
