### ISSUE TITLE
[Remoto] Engenheiro(a) de Dados Pleno CLT na [EloGroup]

### ISSUE THREAD

**Issue by ghost** [datascience-br/vagas#96]
## Descrição da vaga

Você gosta de gerenciar dados e transformá-los em informações relevantes? Domina processos e procedimentos de coleta, armazenamento e disponibilização de dados? Se sente confortável trabalhando em ambiente Big Data? Então venha fazer parte deste time!! Venha ser Elogroup!!

Responsabilidades
-Responsável pelos projetos de coleta, processamento, armazenamento e fornecimento de dados.
-Apoio em projetos de consultoria de gestão, como em projetos de características exclusivamente técnica.
-Implementação em em colocar em produção os modelos e analises desenvolvidas em conjunto com as equipes de cientistas de dados.

## Local

Remoto.

## Benefícios
- Vale Alimentação.
-Vale Refeição.
-Plano de Saúde e Odontológico.
-Seguro de Vida.

## Requisitos

O que você precisa conhecer
-Experiencia em cloud.
-Conhecimento em linguagem SQL.
-Conhecimento em Banco de Dados Relacional, Dimensional e NOSQL.
-Experiencia em criação de processos de carga de dados batch (Airflow, ODI, Pentaho) e streaming (Kafka, NIFI).
-Sólido conhecimento em linguagem de programação Phyton ou Scala.
-Experiencia em construção APIs.
-Experiência profissional de nível Pleno (ter atuado profissionalmente em projetos/empresas).

Pra ter aquela vantagem extra
-Conhecimento de arquitetura Big Data.
-Certificações da área.

## Contratação

- CLT.

## Nossa empresa

UMA CONSULTORIA COM DNA EMPREENDEDOR
Nossa maior entrega é resolver o desafio do cliente.
Para isso, combinamos competências de Tecnologia, Analytics e Gestão para apoiar organizações públicas, privadas e do terceiro setor a gerarem impacto para seus clientes, seus talentos e para a sociedade.
Contamos com mais de 400 EloGroupers, espalhados pelo Brasil, para realizar esse propósito e para construir a empresa que sempre sonhamos em trabalhar.
E estamos sempre em busca de novos talentos.

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/61af50397d07330020919523?r=nvgt&c=4740

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by larissabazzo** [comment]
Vaga aberta ainda!
