### ISSUE TITLE
[Remoto] Engenheiro(a) de Dados Sênior CLT na [EloGroup]

### ISSUE THREAD

**Issue by ghost** [datascience-br/vagas#98]
## Descrição da vaga

Você gosta de gerenciar dados e transformá-los em informações relevantes?
Domina processos e procedimentos de coleta, armazenamento e disponibilização de dados?
Se sente confortável trabalhando em ambiente Big Data?
Então venha fazer parte deste time!! Venha ser Elogroup!!
Candidate-se !!

Responsabilidades
-Responsável pelos projetos de coleta, processamento, armazenamento e fornecimento de dados.
-Apoio em projetos de consultoria de gestão, como em projetos de características exclusivamente técnica.
-Implementação em em colocar em produção os modelos e analises desenvolvidas em conjunto com as equipes de cientistas de dados.

## Local

Remoto.

## Benefícios

-Vale Alimentação
-Vale Refeição
-Plano de Saúde e Odontológico
-Seguro de Vida

## Requisitos

-Sólida experiencia em Cloud
-Sólida experiencia em Big Data
-Sólidos conhecimentos em APIs
-Sólidos conhecimentos em Phyton ou Scala
-Sólidos conhecimentos em CDC-Change Data Capture Golden Gate For Big Data ou Debizium)
-Experiência em construção de Data Lakes e/ou Data Warehouses
-Experiência em criação de processos de carga de dados batch (Airflow, ODI, Pentaho) e streaming (Kafka, NIFI, Spark streaming)
-Experiência em Banco de Dados Relacional, Dimensional e NOSQL
-Experiência profissional de nível Sênior (ter atuado profissionalmente em projetos/empresas)
-Certificação AWS

## Contratação

CLT.

## Nossa empresa

UMA CONSULTORIA COM DNA EMPREENDEDOR
Nossa maior entrega é resolver o desafio do cliente.
Para isso, combinamos competências de Tecnologia, Analytics e Gestão para apoiar organizações públicas, privadas e do terceiro setor a gerarem impacto para seus clientes, seus talentos e para a sociedade.
Contamos com mais de 400 EloGroupers, espalhados pelo Brasil, para realizar esse propósito e para construir a empresa que sempre sonhamos em trabalhar.
E estamos sempre em busca de novos talentos.

## Como se candidatar
Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/62da8920d1705b0020f75ec7?r=srch&c=4740

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista, ou para feedback negativo.

**Comment by larissabazzo** [comment]
Veja também a vaga de nível Pl: https://github.com/datascience-br/vagas/issues/96
